# Generated by Django 5.1.5 on 2025-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_max_purchase_quantity_per_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending_refund', 'Pending Refund'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
    ]
