# Generated by Django 5.1.5 on 2025-12-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
