# Generated by Django 5.1.5 on 2025-12-31 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_display_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='verified_updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
