# Generated by Django 5.1.5 on 2025-12-31 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_created_by'),
        ('products', '0005_remove_order_processed_at_remove_order_processed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='events.event', verbose_name='Event')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='products.productcategory', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Event Product Category',
                'verbose_name_plural': 'Event Product Categories',
                'ordering': ['-added_at'],
                'unique_together': {('event', 'category')},
            },
        ),
    ]
