# Generated by Django 5.1.5 on 2026-01-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_percentage_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproductcategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.product', verbose_name='Product'),
        ),
    ]
