# Generated by Django 5.1.5 on 2026-01-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_eventpermission_options_and_more'),
        ('products', '0008_eventproductcategory_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventproductcategory',
            unique_together={('event', 'category', 'product')},
        ),
    ]
