# Generated by Django 5.1.5 on 2026-01-11 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_eventproductcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_products', through='products.EventProductCategory', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='eventproductcategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_product_categories', to='products.product', verbose_name='Product'),
        ),
    ]
