# Generated by Django 5.1.5 on 2026-01-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_bookingintent_complete_delete_at_and_more'),
        ('products', '0010_product_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_package',
            field=models.ForeignKey(blank=True, help_text='Booking package this order was created from, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bookings.bookingpackage'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package_product',
            field=models.ForeignKey(blank=True, help_text='PackageProduct this item was created from, if part of a booking package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='bookings.packageproduct'),
        ),
    ]
