# Generated by Django 5.1.5 on 2026-05-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_original_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending_refund', 'Pending Refund'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
    ]
