# Generated by Django 5.1.5 on 2026-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending_refund', 'Pending Refund'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
