# Generated by Django 5.1.5 on 2026-05-06 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_orderitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, help_text='External event ID (e.g., Stripe event_id)', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Type of event (e.g., charge.failed, charge.refunded)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('payload', models.JSONField(help_text='Complete webhook payload')),
                ('first_received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('order_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-first_received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_quantity', models.PositiveIntegerField(help_text='Stock quantity before change')),
                ('new_quantity', models.PositiveIntegerField(help_text='Stock quantity after change')),
                ('change_amount', models.IntegerField(help_text='Net change (positive=increment, negative=decrement)')),
                ('change_reason', models.CharField(choices=[('initial_order_deduction', 'Initial Order Deduction'), ('order_cancellation_restore', 'Order Cancellation Restore'), ('payment_failure_restore', 'Payment Failure Restore'), ('refund_restoration', 'Refund Restoration'), ('partial_refund_restoration', 'Partial Refund Restoration'), ('manual_adjustment', 'Manual Adjustment'), ('admin_action', 'Admin Action'), ('stock_restoration_safety_net', 'Stock Restoration Safety Net')], db_index=True, max_length=50)),
                ('order_id', models.UUIDField(blank=True, db_index=True, help_text='Associated Order UUID if applicable', null=True)),
                ('payment_id', models.UUIDField(blank=True, db_index=True, help_text='Associated Payment UUID if applicable', null=True)),
                ('order_item_id', models.BigIntegerField(blank=True, help_text='Associated OrderItem database ID if applicable', null=True)),
                ('webhook_event_id', models.CharField(blank=True, db_index=True, help_text='Stripe webhook event ID for idempotency', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, help_text='Session or request ID for tracing multiple related operations', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context or notes', null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_audit_logs', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Audit Log',
                'verbose_name_plural': 'Stock Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStockLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id', models.UUIDField(db_index=True, help_text='UUID of associated Payment')),
                ('link_type', models.CharField(choices=[('initial_deduction', 'Initial Deduction (Order Created)'), ('refund_restoration', 'Refund Restoration'), ('failure_rollback', 'Failure Rollback'), ('cancellation_restoration', 'Cancellation Restoration')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_audit_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='products.stockauditlog')),
            ],
            options={
                'verbose_name': 'Payment Stock Link',
                'verbose_name_plural': 'Payment Stock Links',
            },
        ),
        migrations.CreateModel(
            name='RefundRollbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payment_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('validating', 'Validating'), ('validation_failed', 'Validation Failed'), ('restoring', 'Restoring'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='initiated', max_length=20)),
                ('snapshot_before', models.JSONField(help_text='Order state snapshot before rollback')),
                ('snapshot_after', models.JSONField(blank=True, help_text='Order state snapshot after rollback', null=True)),
                ('validation_issues', models.JSONField(blank=True, default=list, help_text='List of validation issues found in snapshot')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_rollbacks_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund Rollback Log',
                'verbose_name_plural': 'Refund Rollback Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id', '-created_at'], name='products_re_order_i_069155_idx'), models.Index(fields=['payment_id', '-created_at'], name='products_re_payment_7f9141_idx'), models.Index(fields=['status'], name='products_re_status_6ae1dd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['product_variant', '-created_at'], name='products_st_product_027cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['order_id', '-created_at'], name='products_st_order_i_81d418_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['payment_id', '-created_at'], name='products_st_payment_12d504_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['webhook_event_id'], name='products_st_webhook_7da9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentstocklink',
            index=models.Index(fields=['payment_id', '-created_at'], name='products_pa_payment_a6d481_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentstocklink',
            unique_together={('payment_id', 'stock_audit_log')},
        ),
    ]
