# Generated by Django 5.1.5 on 2026-05-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_webhookevent_stockauditlog_paymentstocklink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_purchase_quantity_per_order',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
