# Generated by Django 5.1.5 on 2025-12-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="url_safe_title",
            field=models.CharField(
                blank=True, help_text="URL safe title", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(help_text="display title", max_length=200),
        ),
    ]
