# Generated by Django 5.1.5 on 2025-12-24 20:07

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_url_safe_title_alter_event_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_datetime__lt", models.F("end_datetime"))),
                name="check_start_before_end_datetime",
                violation_error_message="Event start_datetime must be before end_datetime.",
            ),
        ),
    ]
