# Generated by Django 5.1.5 on 2025-12-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventreview_eventauthorization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="display_identifier",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
