# Generated by Django 5.1.5 on 2025-12-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_display_identifier_alter_eventtype_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventPermmission",
            new_name="EventPermission",
        ),
    ]
