# Generated by Django 5.1.5 on 2025-12-25 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0003_alter_attendee_attendee_display_id_and_more"),
        ("events", "0006_rename_eventpermmission_eventpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("question_title", models.CharField(max_length=255)),
                ("question_body", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("short_answer", "Short Answer"),
                            ("long_answer", "Long Answer"),
                            ("upload", "Upload"),
                            ("multiple_choice", "Multiple Choice"),
                            ("single_choice", "Single Choice"),
                            ("slider", "Slider"),
                        ],
                        default="short_answer",
                        max_length=32,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("public", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("max_value", models.IntegerField(blank=True, null=True)),
                ("min_value", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_answers",
                        to="attendee.attendee",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="events.eventquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="events.eventquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventQuestionAnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_options",
                        to="events.eventquestionanswer",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_in_answers",
                        to="events.eventquestionoption",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="eventquestion",
            constraint=models.UniqueConstraint(
                fields=("event", "order"), name="unique_question_order_per_event"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventquestionanswer",
            unique_together={("question", "attendee")},
        ),
        migrations.AddConstraint(
            model_name="eventquestionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_option_order_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventquestionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "option_text"),
                name="unique_option_text_per_question",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventquestionanswerchoice",
            unique_together={("answer", "option")},
        ),
    ]
