# Generated by Django 5.1.5 on 2025-12-25 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_eventquestion_eventquestionanswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventroleassignment",
            unique_together={("event", "user", "role")},
        ),
    ]
