# Generated by Django 5.1.5 on 2025-12-26 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_eventroleassignment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="display_code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="display_identifier",
            field=models.CharField(
                blank=True,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(20),
                ],
            ),
        ),
    ]
