# Generated by Django 5.1.5 on 2025-12-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_display_code_and_more'),
        ('organisations', '0004_organisation_required_acceptance_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organisation',
            field=models.ForeignKey(help_text='The organisation hosting this event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organisations.organisation', verbose_name='Organisation'),
        ),
    ]
