# Generated by Django 5.1.5 on 2025-12-30 11:14

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventstaff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_enabled', models.BooleanField(default=False, help_text='Whether payment processing is enabled for this event. Note that disabling this will also disable donations, refunds, and product selling.')),
                ('product_publication_requires_verification', models.BooleanField(default=False, help_text='Whether products for this event require verification before being purchasable.')),
                ('product_selling_enabled', models.BooleanField(default=True, help_text='Whether selling products is enabled for this event.')),
                ('donation_enabled', models.BooleanField(default=False, help_text='Whether donations are enabled for this event.')),
                ('refunds_enabled', models.BooleanField(default=False, help_text='Whether refunds are enabled for this event.')),
                ('accepting_sponsorships_enabled', models.BooleanField(default=False, help_text='Whether accepting sponsorships is enabled for this event.')),
                ('participants_registration_require_verification', models.BooleanField(default=False, help_text='Whether participants for this event require manual event staff verification before being fully registered.')),
                ('default_timezone', timezone_field.fields.TimeZoneField(default='Europe/London')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Setting',
                'verbose_name_plural': 'Event Settings',
            },
        ),
    ]
