# Generated by Django 5.1.5 on 2025-12-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsettings',
            name='product_selling_enabled',
            field=models.BooleanField(default=False, help_text='Whether selling products is enabled for this event.'),
        ),
    ]
