# Generated by Django 5.1.5 on 2026-01-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpermission',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='eventquestionanswer',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='eventrole',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='eventstaff',
            options={'ordering': ['-assigned_at']},
        ),
    ]
