# Generated by Django 5.1.5 on 2026-01-11 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_eventpermission_options_and_more'),
        ('locations', '0002_arealocation_unique_area_code_per_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('event_venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_venues', to='events.event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_venues', to='locations.venue')),
            ],
            options={
                'verbose_name': 'Event Venue',
                'verbose_name_plural': 'Event Venues',
            },
        ),
    ]
