# Generated by Django 5.1.5 on 2026-01-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='products_require_approval',
            field=models.BooleanField(default=False, help_text='Whether products for this event require admin approval before being purchasable.'),
        ),
    ]
