# Generated by Django 5.1.5 on 2026-01-12 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_booking_reference'),
        ('events', '0017_eventsettings_products_require_approval'),
        ('payments', '0013_payment_stripe_customer_id_and_more'),
        ('products', '0011_order_booking_package_orderitem_package_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='orders_require_approval',
            field=models.BooleanField(default=True, help_text='Whether orders for this event require manual approval before being auto-processed on payment completion. If False, orders will automatically transition to PROCESSING status when payment completes.'),
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_FULFILLMENT', 'Order Fulfillment Required'), ('BOOKING_CONFIRMATION', 'Booking Confirmed'), ('REFUND_REQUEST', 'Refund Requested'), ('PAYMENT_FAILED', 'Payment Failed'), ('CAPACITY_WARNING', 'Capacity Warning'), ('AUTHORIZATION_REQUEST', 'Authorization Request'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether this notification has been read/acknowledged')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for rendering notification content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered this notification (null for system-generated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='Event this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('related_booking', models.ForeignKey(blank=True, help_text='Booking associated with this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
                ('related_order', models.ForeignKey(blank=True, help_text='Order associated with this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.order')),
                ('related_payment', models.ForeignKey(blank=True, help_text='Payment associated with this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Event Notification',
                'verbose_name_plural': 'Event Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'is_read'], name='events_even_event_i_6fba1c_idx'), models.Index(fields=['notification_type', 'priority'], name='events_even_notific_ac98c2_idx'), models.Index(fields=['created_at'], name='events_even_created_c69819_idx')],
            },
        ),
    ]
