# Generated by Django 5.1.5 on 2026-01-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventsettings_orders_require_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='auto_complete_orders',
            field=models.BooleanField(default=False, help_text='Whether paid orders should automatically transition to COMPLETED status. If True, orders will go directly to COMPLETED after payment (for digital/virtual products). If False, orders will go to PROCESSING and require manual fulfillment completion.'),
        ),
    ]
