# Generated by Django 5.1.5 on 2026-01-25 11:17

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_eventstaffinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpermissionassignment',
            options={'verbose_name': 'Event Permission Assignment', 'verbose_name_plural': 'Event Permission Assignments'},
        ),
        migrations.AddField(
            model_name='eventpermissionassignment',
            name='allow_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpermissionassignment',
            name='allow_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpermissionassignment',
            name='allow_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpermissionassignment',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventpermission',
            name='permission_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventpermissionassignment',
            unique_together={('event', 'user', 'permission')},
        ),
    ]
