# Generated by Django 5.1.5 on 2026-01-27 10:38

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_eventpermissionassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventquestion',
            name='unique_question_order_per_event',
        ),
        migrations.AddConstraint(
            model_name='eventquestion',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('event', 'order'), name='unique_question_order_per_event'),
        ),
    ]
