# Generated by Django 5.1.5 on 2026-01-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_eventquestion_unique_question_order_per_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaffinvite',
            name='permission_template',
            field=models.CharField(blank=True, help_text='Code of the permission template to apply when invite is accepted', max_length=50, null=True),
        ),
    ]
