# Generated by Django 5.1.5 on 2026-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_eventstaffinvite_permission_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpermission',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General Permissions'), ('REGISTRATION', 'Registration Permissions'), ('PRODUCT_MANAGEMENT', 'Product Management Permissions'), ('CONTENT_MANAGEMENT', 'Content Management Permissions'), ('STAFF_MANAGEMENT', 'Staff Management Permissions'), ('PAYMENT_MANAGEMENT', 'Payment Management Permissions'), ('BOOKING_MANAGEMENT', 'Booking Management Permissions'), ('RESOURCE_MANAGEMENT', 'Resource Management Permissions'), ('REPORTING', 'Reporting Permissions')], default='GENERAL', max_length=30),
        ),
    ]
