# Generated by Django 5.1.5 on 2026-03-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_eventsettings_sponsor_checkout_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='max_attendees_per_booking',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of attendees that can be included in a single booking.'),
        ),
    ]
