# Generated by Django 5.1.5 on 2026-03-28 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventsettings_max_attendees_per_booking'),
        ('organisations', '0010_eventsponsorinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url_safe_title',
            field=models.CharField(blank=True, db_index=True, help_text='URL safe title', max_length=200, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['url_safe_title'], name='events_even_url_saf_799ad0_idx'),
        ),
    ]
