# Generated by Django 5.1.5 on 2026-04-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_event_url_safe_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_event',
            field=models.BooleanField(default=False, help_text='Whether this event is primarily external and only listed on the platform for visibility. External events will not have registration or product selling features enabled.'),
        ),
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.URLField(blank=True, help_text='External link for the event, e.g. a website or registration page.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_closed',
            field=models.DateTimeField(blank=True, help_text='The last time this event was closed for registration.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_opened',
            field=models.DateTimeField(blank=True, help_text='The last time this event was opened for registration.', null=True),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='max_attendees_per_user',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of attendees that a single user can register across all their bookings for this event.'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='max_attendees_per_booking',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of attendees that can be included in a single booking.'),
        ),
    ]
