# Generated by Django 5.1.5 on 2026-05-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_eventnotification_unique_notification_per_payment_order'),
        ('locations', '0004_arealocation_latitude_arealocation_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(help_text='The location where the event is taking place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.arealocation', verbose_name='Event Location'),
        ),
    ]
