# Generated by Django 5.1.5 on 2026-05-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_event_location'),
        ('locations', '0004_arealocation_latitude_arealocation_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location where the event is taking place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.arealocation', verbose_name='Event Location'),
        ),
    ]
