# Generated by Django 5.1.5 on 2026-05-13 08:40

import core.utils.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVenueContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[core.utils.validators.PhoneNumberValidator()])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('OWNER', 'Owner'), ('COORDINATOR', 'Coordinator'), ('SUPPORT', 'Support'), ('OTHER', 'Other')], default='OWNER', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventVenueMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventVenueRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventvenue',
            name='venue',
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='address',
            field=models.TextField(default='BASE_ADDRESS', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='name',
            field=models.CharField(default='BASE_NAME', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='poi_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='source_venue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='eventvenue',
            constraint=models.UniqueConstraint(condition=models.Q(('source_venue_id__isnull', False)), fields=('event', 'source_venue_id'), name='unique_event_source_venue'),
        ),
        migrations.AddField(
            model_name='eventvenuecontact',
            name='event_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='events.eventvenue'),
        ),
        migrations.AddField(
            model_name='eventvenuemetadata',
            name='event_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='events.eventvenue'),
        ),
        migrations.AddField(
            model_name='eventvenueroom',
            name='event_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='events.eventvenue'),
        ),
    ]
