# Generated by Django 5.1.5 on 2026-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_eventvenuecontact_eventvenuemetadata_eventvenueroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed_message',
            field=models.TextField(blank=True, help_text='Optional message to display to users when the event is closed for registration.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='published_message',
            field=models.TextField(blank=True, help_text='Optional message to display to users when the event is published but not yet open for registration.', null=True),
        ),
    ]
