# Generated by Django 5.1.5 on 2026-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_event_closed_message_event_published_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvenue',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates the primary venue for the event when multiple venues are present.'),
        ),
    ]
