# Generated by Django 5.1.5 on 2026-06-04 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_eventvenue_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreview',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the review is visible to others.'),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether the review has been approved by an organiser or admin.'),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment about the event.', null=True),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rating for the event, on a scale of 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
