# Generated by Django 5.1.5 on 2026-06-08 21:00

import apps.events.models.forms.responses
import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0024_attendeecheckin_event_day_and_more'),
        ('events', '0036_eventtransportoption_eventtransportschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='draft', max_length=16)),
                ('required', models.BooleanField(default=False, help_text='Whether all attendees are required to complete this form.')),
                ('allow_response_editing', models.BooleanField(default=True, help_text='Allow attendees to edit their responses until the form is closed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_forms', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255)),
                ('question_body', models.TextField()),
                ('question_type', models.CharField(choices=[('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('upload', 'Upload'), ('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('slider', 'Slider'), ('date', 'Date'), ('time', 'Time'), ('email', 'Email'), ('phone', 'Phone'), ('rating', 'Rating'), ('None', ' Range Types')], default='short_answer', max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.eventform')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFormQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='events.eventformquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventFormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='attendee.attendee')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.eventform')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFormDelegateToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_delegate_tokens', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_tokens', to='events.eventformresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFormResponseAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_file', models.FileField(blank=True, null=True, storage='core.storage_backends.MediaStorage', upload_to=apps.events.models.forms.responses._form_response_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.eventformquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.eventformresponse')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFormResponseAnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='events.eventformresponseanswer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_in_answers', to='events.eventformquestionoption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventformquestion',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('form', 'order'), name='unique_form_question_order_per_form'),
        ),
        migrations.AddConstraint(
            model_name='eventformquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_form_option_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='eventformquestionoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_text'), name='unique_form_option_text_per_question'),
        ),
        migrations.AddConstraint(
            model_name='eventformresponse',
            constraint=models.UniqueConstraint(fields=('form', 'attendee'), name='unique_form_response_per_attendee'),
        ),
        migrations.AddConstraint(
            model_name='eventformresponseanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_form_answer_per_question_per_response'),
        ),
        migrations.AlterUniqueTogether(
            name='eventformresponseanswerchoice',
            unique_together={('answer', 'option')},
        ),
    ]
