# Generated by Django 5.1.5 on 2026-06-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_eventform_eventformquestion_eventformquestionoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventformquestion',
            name='question_type',
            field=models.CharField(choices=[('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('upload', 'Upload'), ('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('slider', 'Slider'), ('date', 'Date'), ('time', 'Time'), ('email', 'Email'), ('phone', 'Phone'), ('rating', 'Rating')], default='short_answer', max_length=32),
        ),
    ]
