# Generated by Django 5.1.5 on 2026-06-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_alter_eventformquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventform',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Optional deadline for form submission. Ignored if the form is closed.', null=True),
        ),
        migrations.AddField(
            model_name='eventform',
            name='deadline_message',
            field=models.CharField(blank=True, help_text='Optional message to display when the deadline has passed.', max_length=255),
        ),
        migrations.AddField(
            model_name='eventform',
            name='opens_at',
            field=models.DateTimeField(blank=True, help_text='Optional opening time for the form. Ignored if the form is published.', null=True),
        ),
        migrations.AddField(
            model_name='eventform',
            name='pre_opens_message',
            field=models.CharField(blank=True, help_text='Optional message to display before the form opens.', max_length=255),
        ),
    ]
