# Generated by Django 5.1.5 on 2026-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_eventform_deadline_eventform_deadline_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventform',
            name='landing_image',
            field=models.ImageField(blank=True, help_text='Optional image to display on the form landing page.', null=True, upload_to='event_forms/landing_images/'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_FULFILLMENT', 'Order Fulfillment Required'), ('BOOKING_CONFIRMATION', 'Booking Confirmed'), ('REFUND_REQUEST', 'Refund Requested'), ('REFUND_UPDATE', 'Refund Updated'), ('REFUND_APPROVAL', 'Refund Approval Needed'), ('REFUND_PROCESSED', 'Refund Processed'), ('REFUND_REJECTION', 'Refund Rejected'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_UPDATE', 'Payment Updated'), ('CAPACITY_WARNING', 'Capacity Warning'), ('AUTHORIZATION_REQUEST', 'Authorization Request'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=50),
        ),
    ]
