# Generated by Django 5.1.5 on 2026-09-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_eventform_landing_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_external_events', models.BooleanField(default=False)),
                ('allow_attendee_deletions', models.BooleanField(default=False)),
                ('allow_workshops', models.BooleanField(default=True)),
                ('allow_product_releases', models.BooleanField(default=True)),
                ('allow_sponsors', models.BooleanField(default=True)),
                ('require_long_description', models.BooleanField(default=False)),
                ('require_short_description', models.BooleanField(default=False)),
                ('require_landing_image', models.BooleanField(default=False)),
                ('product_release_must_be_approved_by_organisation', models.BooleanField(default=True)),
                ('must_be_approved_by_organisation', models.BooleanField(default=True)),
                ('max_attendees_per_event', models.PositiveIntegerField(default=100)),
                ('card_payments_are_allowed', models.BooleanField(default=True)),
                ('bank_transfers_are_allowed', models.BooleanField(default=True)),
                ('max_package_price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='events.event')),
            ],
        ),
    ]
