# Generated by Django 5.1.5 on 2026-06-09 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendee', '0025_attendeenote'),
        ('events', '0038_alter_eventformquestion_question_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('verified_updated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_processed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the workshop')),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions for the workshop', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current lifecycle status of the workshop.', max_length=20)),
                ('allocation_mode', models.CharField(choices=[('FCFS', 'First Come First Served'), ('INTEREST_RANKING', 'Interest Ranking'), ('RANDOM', 'Random'), ('MANUAL', 'Manual')], default='FCFS', help_text='How attendee spots are allocated for this workshop.', max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of confirmed registrations. Leave blank for unlimited.', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration of the workshop in minutes.', null=True)),
                ('registration_opens_at', models.DateTimeField(blank=True, help_text='When registration opens. Informational — does not enforce access automatically.', null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, help_text='When registration closes. Informational — does not enforce access automatically.', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='events.event')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='events.eventvenueroom')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='events.eventvenue')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopInterestSubmission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_finalised', models.BooleanField(default=False, help_text='When True the submission is locked and ready for allocation.')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_interest_submissions', to='attendee.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_interest_submissions', to='events.event')),
            ],
            options={
                'verbose_name': 'Workshop Interest Submission',
                'verbose_name_plural': 'Workshop Interest Submissions',
                'unique_together': {('event', 'attendee')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopInterestRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Preference rank for this workshop (1 = most preferred).')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_ranks', to='workshops.workshop')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='workshops.workshopinterestsubmission')),
            ],
            options={
                'verbose_name': 'Workshop Interest Rank',
                'verbose_name_plural': 'Workshop Interest Ranks',
                'ordering': ['rank'],
                'unique_together': {('submission', 'rank'), ('submission', 'workshop')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('verified_updated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_processed', models.BooleanField(default=False)),
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(blank=True, help_text='Unique reference code for the workshop registration. Auto-generated if not provided.', max_length=50, null=True, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING_ALLOCATION', 'Pending Allocation'), ('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', help_text='Allocation status for this registration.', max_length=20)),
                ('allocation_method', models.CharField(blank=True, choices=[('FCFS', 'First Come First Served'), ('INTEREST_RANKING', 'Interest Ranking'), ('RANDOM', 'Random'), ('MANUAL', 'Manual')], help_text='Which allocation method produced this registration.', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes about this registration.', null=True)),
                ('allocated_by', models.ForeignKey(blank=True, help_text='Staff member who manually confirmed this registration (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to='attendee.attendee')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Workshop Registration',
                'verbose_name_plural': 'Workshop Registrations',
                'unique_together': {('workshop', 'attendee')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('verified_updated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_processed', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('INSTRUCTOR', 'Instructor'), ('ASSISTANT', 'Assistant'), ('LEADER', 'Leader'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Additional notes about the staff member's role or responsibilities for the workshop", null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_staff_added', to=settings.AUTH_USER_MODEL)),
                ('event_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_staff_roles', to='events.eventstaff')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Workshop Staff',
                'verbose_name_plural': 'Workshop Staff',
                'unique_together': {('workshop', 'event_staff')},
            },
        ),
    ]
