# Generated by Django 5.1.5 on 2026-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='landing_image',
            field=models.ImageField(blank=True, help_text='Optional image to display on the workshop landing page', null=True, upload_to='workshop_images/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='what_to_bring',
            field=models.TextField(blank=True, help_text='Information about what attendees should bring to the workshop', null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='what_to_expect',
            field=models.TextField(blank=True, help_text='Information about what attendees can expect from the workshop', null=True),
        ),
    ]
