"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/

IMPORTANT - AWS SSM USAGE:
==============================
ALL secrets are loaded from SSM Parameter Store in a SINGLE batch call at startup.
This prevents KMS quota exhaustion from repeated decrypt operations.

DO NOT add runtime SSM calls anywhere in the application:
- NO get_parameter() calls in views, tasks, or middleware
- ALL secrets must be loaded via get_secret() which uses startup cache
- New secrets must be added to REQUIRED_SECRETS list below
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta

# Load .env file for local development
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# SENTRY CONFIGURATION (Toggleable)
# =============================================================================
SENTRY_ENABLED = os.getenv("SENTRY_ENABLED", "False") == "True"
SENTRY_DSN = os.getenv("SENTRY_DSN", "")

import logging

logger = logging.getLogger(__name__)

if SENTRY_ENABLED and SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
        profiles_sample_rate=float(os.getenv("SENTRY_PROFILES_SAMPLE_RATE", "0.1")),
        send_default_pii=True,
        environment=os.getenv("ENVIRONMENT", "development"),
    )

# =============================================================================
# AWS SSM PARAMETER STORE CONFIGURATION
# =============================================================================
USE_SSM = True
SSM_PARAM_PREFIX = os.getenv("SSM_PARAM_PREFIX", "/prod/amdg/v1/")

ssm_client = None
_SECRET_CACHE = {}  # In-memory cache for secrets loaded at startup

# Define all required secret keys upfront (MAX 10 for single batch read)
REQUIRED_SECRETS = [
    'SECRET_KEY',
    'DEBUG',
    'ALLOWED_HOSTS',
    'DB_ENGINE',
    'DB_NAME',
    'DB_USER',
    'DB_PASSWORD',
    'DB_HOST',
    'DB_PORT',
    'AWS_STORAGE_BUCKET_NAME',
    'AWS_S3_REGION_NAME',
    'AWS_ACCESS_KEY_ID',
    'AWS_SECRET_ACCESS_KEY'
]

if USE_SSM:
    try:
        print("Using SSM")
        import boto3
        from botocore.exceptions import ClientError, NoCredentialsError
        
        ssm_client = boto3.client('ssm', region_name=os.getenv("AWS_REGION", "eu-west-2"))
        if ssm_client is None:
            raise RuntimeError("ssm client is none")
        sts = boto3.client('sts')
        sts.get_caller_identity()
        print("SSM config complete")

    except (ImportError, NoCredentialsError) as e:
        logger.warning(f"WARNING: Could not initialize SSM client: {e}")
        USE_SSM = False
else:
    print("SSM is not in use, .env only in use")


def _chunked(iterable, size=10):
    for i in range(0, len(iterable), size):
        yield iterable[i:i + size]


def _load_all_secrets_from_ssm():
    """Load ALL secrets from SSM Parameter Store in a single batch call at startup."""
    if not USE_SSM or not ssm_client:
        print("not loading secrets due to disabled!")
        return
    
    try:
        param_names = [f"{SSM_PARAM_PREFIX}{secret}" for secret in REQUIRED_SECRETS]
        print(param_names)
        # SSM allows max 10 parameters per get_parameters call
        for chunk in _chunked(param_names, 10):
            response = ssm_client.get_parameters(
                Names=chunk,
                WithDecryption=True
            )
            for param in response['Parameters']:
                # Strip the prefix to get the secret name
                secret_name = param['Name'].replace(SSM_PARAM_PREFIX, '')
                _SECRET_CACHE[secret_name] = param['Value']
            
            # Log any invalid parameters
            if response.get('InvalidParameters'):
                logger.warning(f"WARNING: Invalid SSM parameters: {response['InvalidParameters']}")
        print("finished loading ssm params")
    except Exception as e:
        print("an error occured in ssm params")
        logger.error(f"ERROR loading secrets from SSM: {e}")
        logger.error("Falling back to environment variables")

# Load secrets at startup
_load_all_secrets_from_ssm()

print("secrets cache :" + str(_SECRET_CACHE))
print("ssm :" + str(ssm_client))

def get_secret(name, default=None):
    """
    Get a secret from the cache (populated at startup) or fall back to environment variables.
    
    DO NOT call boto3 SSM client here - all secrets are pre-loaded at startup.
    """
    if USE_SSM and name in _SECRET_CACHE:
        return _SECRET_CACHE[name]
    return os.getenv(name, default)


# =============================================================================
# CORE DJANGO SETTINGS
# =============================================================================
SECRET_KEY = get_secret('SECRET_KEY', 'django-insecure-gyht1$pi@_=gdkw$lr&6zuv+k0w6e@0o9p&56$94w*gv8cr!6q')
DEBUG = get_secret("DEBUG", "True") == "True"
ALLOWED_HOSTS = get_secret("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Custom User Model
AUTH_USER_MODEL = "users.CommunityUser"

# =============================================================================
# APPLICATION DEFINITION
# =============================================================================
DJANGO_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'storages',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_filters',
    'corsheaders',
    'channels',
    'django_celery_beat',
    'django_celery_results',
    'djmoney',
    'timezone_field',
    'colorfield',
    'imagekit',
    'qr_code',
]

LOCAL_APPS = [
    "core",
    "apps.users.apps.UsersConfig",
    "apps.locations.apps.LocationsConfig",
    "apps.organisations.apps.OrganisationsConfig",
    "apps.events.apps.EventsConfig",
    "apps.common.apps.CommonConfig",
    "apps.payments.apps.PaymentsConfig",
    "apps.attendee.apps.AttendeeConfig",
    "apps.products.apps.ProductsConfig",
    "apps.bookings.apps.BookingsConfig",
    "apps.workshops.apps.WorkshopsConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# =============================================================================
# MIDDLEWARE
# =============================================================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# =============================================================================
# TEMPLATES
# =============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
# Use PostgreSQL in production/docker, fallback to SQLite for local if specified
USE_POSTGRES = get_secret("USE_POSTGRES", "True") == "True"

if USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': get_secret('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': get_secret('DB_NAME', 'amdg_db'),
            'USER': get_secret('DB_USER', 'postgres'),
            'PASSWORD': get_secret('DB_PASSWORD', ''),
            'HOST': get_secret('DB_HOST', 'localhost'),
            'PORT': get_secret('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/London'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# =============================================================================
# STATIC & MEDIA FILES (AWS S3)
# =============================================================================
USE_S3 = get_secret("USE_S3", "False") == "True"

if USE_S3:
    # AWS S3 Settings
    #AWS_ACCESS_KEY_ID = get_secret("AWS_ACCESS_KEY_ID", "")
    #AWS_SECRET_ACCESS_KEY = get_secret("AWS_SECRET_ACCESS_KEY", "")
    #AWS_STORAGE_BUCKET_NAME = get_secret("AWS_STORAGE_BUCKET_NAME", "")
    #AWS_S3_REGION_NAME = get_secret("AWS_S3_REGION_NAME", "eu-west-2")
    #AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    #AWS_S3_OBJECT_PARAMETERS = {
    #    'CacheControl': 'max-age=86400',
    #}
    #AWS_DEFAULT_ACL = 'public-read'
    #AWS_LOCATION = 'static'
    #AWS_QUERYSTRING_AUTH = False

    # Static files
    #STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    #STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

    # Media files
    #DEFAULT_FILE_STORAGE = 'core.storage_backends.MediaStorage'
    #MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    AWS_STORAGE_BUCKET_NAME = get_secret("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = get_secret("AWS_S3_REGION_NAME")

    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400"
    }
    # STATICFILES_STORAGE = "core.storage.StaticStorage"
    # DEFAULT_FILE_STORAGE = "core.storage.MediaStorage"

    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
                "OPTIONS": {
                    "bucket_name": AWS_STORAGE_BUCKET_NAME,
                    "region_name": AWS_S3_REGION_NAME,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "location": "static",  # Folder in the bucket for static files
                "file_overwrite": False,
        },
    },
    }
    
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
else:
    # Local static/media files
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# =============================================================================
# DJANGO-IMAGEKIT CONFIGURATION
# =============================================================================
# Variants are stored alongside originals in whatever storage backend is active.
# Filenames are content-hash-addressed by imagekit — safe for immutable CDN caching.
IMAGEKIT_DEFAULT_FILE_STORAGE = 'core.storage_backends.VariantMediaStorage'
IMAGEKIT_CACHEFILE_DIR = 'resources/images/CACHE'
# Optimistic: generate lazily on first .url access, then cache the file.
IMAGEKIT_CACHEFILE_DEFAULT_CACHEFILE_STRATEGY = 'imagekit.cachefiles.strategies.Optimistic'
# =============================================================================
# CORS CONFIGURATION
# =============================================================================
CORS_ALLOWED_ORIGINS = get_secret(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000"
).split(",")

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = get_secret("CORS_ALLOW_ALL_ORIGINS", "False") == "True"

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# =============================================================================
# CSRF CONFIGURATION (for cookie-based auth)
# =============================================================================
CSRF_TRUSTED_ORIGINS = get_secret(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000"
).split(",")

CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_DOMAIN = None  # Allow cookies on localhost

# =============================================================================
# SESSION CONFIGURATION
# =============================================================================
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_DOMAIN = None  # Allow cookies on localhost

# =============================================================================
# DJANGO REST FRAMEWORK
# =============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.JWTCookieAuthentication',  # Custom cookie-based JWT auth
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'URL_FORMAT_OVERRIDE': None,  # Disable DRF's ?format= content negotiation to allow custom format parameter
}

# =============================================================================
# SIMPLE JWT CONFIGURATION (HTTP-Only Cookies)
# =============================================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(get_secret("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "15"))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(get_secret("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7"))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    # HTTP-Only Cookie settings
    'AUTH_COOKIE': 'access',
    'AUTH_COOKIE_REFRESH': 'refresh',
    'AUTH_COOKIE_SECURE': not DEBUG,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_PATH': '/',
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

# =============================================================================
# DRF SPECTACULAR (OpenAPI Schema)
# =============================================================================
def exclude_duplicate_inventory_paths(endpoints, **kwargs):
    """
    Preprocessing hook to exclude router-generated inventory paths from the schema.
    The canonical inventory paths are registered manually at /products/inventory/ and
    /products/inventory/attendees/. The router also generates them at
    /products/list/inventory/ and /products/list/inventory/attendees/, causing operationId
    collisions. We exclude the router-generated duplicates here.
    """
    excluded = {
        '/api/products/list/inventory/',
        '/api/products/list/inventory/attendees/',
    }
    return [(path, path_regex, method, callback)
            for path, path_regex, method, callback in endpoints
            if path not in excluded]


def preprocess_timezone_field(result, generator, request, public):
    """Postprocessing hook to normalize timezone enum names."""
    # Find and rename all timezone enums to a single name
    if 'components' in result and 'schemas' in result['components']:
        schemas = result['components']['schemas']
        timezone_enum_name = 'TimezoneEnum'
        
        # Find all timezone-related enums and consolidate them
        timezone_keys = [k for k in schemas.keys() if 'timezone' in k.lower() and 'Enum' in k]
        
        if timezone_keys:
            # Use the first one as the canonical enum
            first_key = timezone_keys[0]
            canonical_enum = schemas[first_key]
            
            # Replace all references to other timezone enums with the canonical one
            for key in timezone_keys[1:]:
                if key in schemas:
                    del schemas[key]
            
            # Rename the first one to our standard name if needed
            if first_key != timezone_enum_name and first_key in schemas:
                schemas[timezone_enum_name] = schemas.pop(first_key)
    
    return result

SPECTACULAR_SETTINGS = {
    'TITLE': 'AMDG API',
    'DESCRIPTION': 'AMDG Platform API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api',
    'PREPROCESSING_HOOKS': ['core.settings.exclude_duplicate_inventory_paths'],
    'POSTPROCESSING_HOOKS': ['core.settings.preprocess_timezone_field'],
    'ENUM_NAME_OVERRIDES': {
        'EventStatusChoices': 'apps.events.models.events.EventStatusChoices',
        'EventAuthorizationStatusChoices': 'apps.events.models.authorization.EventAuthorizationStatusChoices',
        'PaymentStatusChoices': 'apps.payments.models.payments.PaymentStatusChoices',
        'OrderStatusChoices': 'apps.products.models.orders.OrderStatusChoices',
        'TicketStatusChoices': 'apps.bookings.models.ticket.TicketStatusChoices',
        'BookingIntentStatusChoices': 'apps.bookings.models.booking.BookingIntentStatusChoices',
        'AttendeeRelationshipEnum': 'apps.attendee.models.attendee.AttendeeRelationship',
        'HumanRelationshipEnum': 'apps.attendee.models.groups.HumanRelationshipChoices',
        'AttendeeActionEnum': 'apps.attendee.models.attendee.AttendeeActionChoices',
        'AttendeeMessagePriorityEnum': 'apps.attendee.models.messages.AttendeeMessagePriority',
        'VerificationStatusEnum': 'apps.common.models.verification.VerificationStatus',
        'VenueContactRoleChoices': 'apps.locations.models.venues.VenueContactRoleChoice',
        'InvolvedOrganisationRoleChoices': 'apps.organisations.models.organisation.InvolvedOrganisationRoleChoices',
    },
    'ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE': False,
}

# =============================================================================
# DJANGO CHANNELS (WebSockets)
# =============================================================================
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(
                get_secret("REDIS_HOST", "localhost"),
                int(get_secret("REDIS_PORT", "6379"))
            )],
        },
    },
}

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
CELERY_BROKER_URL = get_secret("CELERY_BROKER_URL", "redis://localhost:6379/1")
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Beat Schedule - Periodic Tasks
CELERY_BEAT_SCHEDULE = {
    'mark-completed-events': {
        'task': 'events.mark_completed_events',
        'schedule': 3600.0,  # Run every hour (3600 seconds)
        'options': {
            'expires': 3000.0,  # Task expires after 50 minutes if not executed
        }
    },
}

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
# Local dev:  EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#             EMAIL_HOST=mailpit (or localhost), EMAIL_PORT=1025
# Production: EMAIL_BACKEND=django_ses.SESBackend
# =============================================================================
EMAIL_BACKEND = get_secret(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
)

if "ses" in EMAIL_BACKEND.lower():
    # AWS SES Configuration (production)
    AWS_SES_REGION_NAME = get_secret("AWS_SES_REGION_NAME", "eu-west-2")
    AWS_SES_REGION_ENDPOINT = f'email.{AWS_SES_REGION_NAME}.amazonaws.com'
    DEFAULT_FROM_EMAIL = get_secret("DEFAULT_FROM_EMAIL", "noreply@rsalarda.works")
    SERVER_EMAIL = get_secret("SERVER_EMAIL", "noreply@rsalarda.works")
else:
    # SMTP fallback — defaults to Mailpit for local development
    # Mailpit SMTP: port 1025 | Mailpit Web UI: port 8025
    EMAIL_HOST = get_secret("EMAIL_HOST", "localhost")
    EMAIL_PORT = int(get_secret("EMAIL_PORT", "1025"))
    EMAIL_USE_TLS = get_secret("EMAIL_USE_TLS", "False") == "True"
    EMAIL_USE_SSL = get_secret("EMAIL_USE_SSL", "False") == "True"
    EMAIL_HOST_USER = get_secret("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = get_secret("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = get_secret("DEFAULT_FROM_EMAIL", "noreply@amdg.local")

# Frontend URL — used when building links included in emails (e.g. password reset)
FRONTEND_URL = get_secret("FRONTEND_URL", "http://localhost:3000")

# Backend base URL — used to resolve relative media URLs in emails and other contexts
# where an absolute URL is required (e.g. embedding images in transactional emails).
# In production this should be the public-facing API domain, e.g. https://api.example.com
BACKEND_URL = get_secret("BACKEND_URL", "http://localhost:8000")

# Password reset token validity in seconds (default: 1 hour)
PASSWORD_RESET_TIMEOUT = int(get_secret("PASSWORD_RESET_TIMEOUT", "3600"))

# =============================================================================
# STRIPE CONFIGURATION
# =============================================================================
STRIPE_TEST_MODE = get_secret("STRIPE_TEST_MODE", "True") == "True"
STRIPE_SECRET_KEY = get_secret(
    "STRIPE_SECRET_KEY_TEST" if STRIPE_TEST_MODE else "STRIPE_SECRET_KEY_LIVE",
    ""
)
STRIPE_PUBLISHABLE_KEY = get_secret(
    "STRIPE_PUBLISHABLE_KEY_TEST" if STRIPE_TEST_MODE else "STRIPE_PUBLISHABLE_KEY_LIVE",
    ""
)
STRIPE_WEBHOOK_SECRET = get_secret("STRIPE_WEBHOOK_SECRET", "")
STRIPE_CONNECT_DEFAULT_COUNTRY = get_secret("STRIPE_CONNECT_DEFAULT_COUNTRY", "GB")

# =============================================================================
# GOOGLE OAUTH (for future implementation)
# =============================================================================
GOOGLE_OAUTH_CLIENT_ID = get_secret("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = get_secret("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_OAUTH_REDIRECT_URI = get_secret("GOOGLE_OAUTH_REDIRECT_URI", "")

# =============================================================================
# SECURITY SETTINGS
# =============================================================================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    
SERIALIZATION_MODULES = {"json": "djmoney.serializers"}

# =============================================================================
# LOGGING
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'colored': {
            '()': 'colorlog.ColoredFormatter',
            'format': (
                '%(log_color)s'
                '[%(levelname)s] '
                '%(asctime)s '
                '%(module)s: '
                '%(message)s'
            ),
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'log_colors': {
                'DEBUG':    'cyan',
                'INFO':     'green',
                'WARNING':  'yellow',
                'ERROR':    'red',
                'CRITICAL': 'bold_red',
            },
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'colored',
        },
    },

    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# =============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# =============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# OTHER
# =============================================================================
MAX_LENGTH_LOCATION_ID = 20
MAX_ID_GENERATION_ATTEMPTS = 5
FULL_DELETE_BOOKING_INTENTS = 10 # days

JAZZMIN_SETTINGS = {
    "site_title": "AMDG Admin",
    "show_ui_builder": True,
    "user_avatar": "profile_picture_url",
    "site_header": "AMDG Admin",
    "site_brand": "AMDG Admin",
    # "site_logo": "images/yfc.png",
    # "site_logo_classes": "img-circle",
    "welcome_sign": "Welcome to the AMDG Admin Portal",
    "copyright": "AMDG Admin Portal",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-gray",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-lightblue",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cyborg",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
