# Generated by Django 5.1.5 on 2025-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountrule',
            name='rule_type',
            field=models.CharField(choices=[('IS_EVENT_STAFF', 'Is Event Staff'), ('IS_AGE_LT', 'Is Age Less Than'), ('IS_AGE_GT', 'Is Age Greater Than'), ('ORGANISATION_MATCHES', 'Organisation Matches'), ('VALUE_MATCHES', 'Value Matches'), ('EVENT_STAFF_ROLE_MATCHES', 'Event Staff Role Matches'), ('NAME_MATCHES', 'Name Matches'), ('LOCATION_MATCHES', 'Location Matches'), ('CODE_MATCHES', 'Code Matches')], default='IS_EVENT_STAFF', max_length=30),
        ),
    ]
