# Generated by Django 5.1.5 on 2026-01-02 11:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='percentage_modifier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage adjustment applied to the base amount (1.1 for +1%, -2.5 for -2.5%)', max_digits=5),
        ),
    ]
