# Generated by Django 5.1.5 on 2026-01-03 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0006_alter_payment_percentage_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RefundAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='payments.refundrequest')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_association_targets', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Refund Association',
                'verbose_name_plural': 'Refund Associations',
                'unique_together': {('refund_request', 'target_type', 'target_id')},
            },
        ),
    ]
