# Generated by Django 5.1.5 on 2026-01-03 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_donation_auto_processed_refundrequest_auto_processed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistoryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_actions', to='payments.payment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History Action',
                'verbose_name_plural': 'Payment History Actions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
