# Generated by Django 5.1.5 on 2026-01-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymenthistoryaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundassociation',
            name='content_type',
        ),
    ]
