# Generated by Django 5.1.5 on 2026-01-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_refundassociation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundassociation',
            name='target_id',
            field=models.CharField(max_length=255),
        ),
    ]
