# Generated by Django 5.1.5 on 2026-01-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_created_by'),
        ('payments', '0011_alter_refundassociation_target_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('non_refundable', 'Non-Refundable')], default='full_refund', max_length=20)),
                ('refundable_within_days', models.PositiveIntegerField(default=14, help_text='Number of days before event start date when full refunds are allowed.')),
                ('percentage_refund', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of the original amount to refund for partial refunds.', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Additional notes regarding the refund policy.')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_policy', to='events.event')),
            ],
            options={
                'verbose_name': 'Refund Policy',
                'verbose_name_plural': 'Refund Policies',
            },
        ),
    ]
