# Generated by Django 5.1.5 on 2026-01-13 17:33

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_payment_base_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='base_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='GBP', max_digits=14, null=True),
        ),
    ]
