# Generated by Django 5.1.5 on 2026-01-13 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_payment_base_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='payments.payment'),
        ),
    ]
