# Generated by Django 5.1.5 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_donation_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='target_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
