# Generated by Copilot on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_banktransferevidence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditexpense',
            name='target_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
