# Generated by Django 5.1.5 on 2026-04-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_creditexpense_target_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_transfer_required_immediately',
            field=models.BooleanField(default=False, help_text='Snapshot of payment method policy at payment creation time.'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_transfer_required_immediately',
            field=models.BooleanField(default=False, help_text='If true, checkout must include bank transfer evidence immediately for this method.'),
        ),
    ]
