# Generated by Django 5.1.5 on 2026-04-28 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_payment_original_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_account_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('account_type', models.CharField(default='express', max_length=30)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('business_type', models.CharField(blank=True, default='', max_length=50)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('details_submitted', models.BooleanField(default=False)),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=255)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_connected_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Connected Account',
                'verbose_name_plural': 'Stripe Connected Accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_account_id'], name='payments_st_stripe__00f62a_idx'), models.Index(fields=['charges_enabled', 'payouts_enabled'], name='payments_st_charges_80b45a_idx')],
            },
        ),
    ]
