# Generated by Django 5.1.5 on 2025-12-24 13:34

import core.utils.validators
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter_name",
                    models.CharField(max_length=150, verbose_name="name-of-chapter"),
                ),
                (
                    "chapter_code",
                    models.CharField(
                        max_length=3, null=True, verbose_name="chapter-code"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="description of the chapter location",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="is-active-chapter"),
                ),
                (
                    "established_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="established-date"
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClusterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_name",
                    models.CharField(max_length=150, verbose_name="name-of-cluster"),
                ),
                (
                    "cluster_code",
                    models.CharField(
                        max_length=3,
                        null=True,
                        unique=True,
                        verbose_name="cluster-code",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="is-active-cluster"),
                ),
                (
                    "established_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="established-date"
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CountryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, unique=True
                    ),
                ),
                (
                    "general_sector",
                    models.CharField(
                        choices=[
                            ("EUROPE", "Europe"),
                            ("ASIA", "Asia"),
                            ("NORTH_AMERICA", "North America"),
                            ("CENTRAL_AMERICA", "Central America"),
                            ("SOUTH_AMERICA", "South America"),
                            ("AFRICA", "Africa"),
                            ("OCEANIA", "Oceania"),
                            ("MIDDLE_EAST", "Middle East"),
                        ],
                        verbose_name="general world sector",
                    ),
                ),
                (
                    "specific_sector",
                    models.CharField(
                        choices=[
                            ("NORTH_EUROPE", "Northern Europe"),
                            ("SOUTH_EUROPE", "Southern Europe"),
                            ("WEST_EUROPE", "Western Europe"),
                            ("EAST_EUROPE", "Eastern Europe"),
                            ("CENTRAL_EUROPE", "Central Europe"),
                            ("EAST_ASIA", "East Asia"),
                            ("SOUTH_ASIA", "South Asia"),
                            ("SOUTHEAST_ASIA", "Southeast Asia"),
                            ("CENTRAL_ASIA", "Central Asia"),
                            ("WEST_ASIA", "Western Asia"),
                            ("NORTH_AMERICA", "North America"),
                            ("CENTRAL_AMERICA", "Central America"),
                            ("CARIBBEAN", "Caribbean"),
                            ("SOUTH_AMERICA_NORTH", "Northern South America"),
                            ("SOUTH_AMERICA_SOUTH", "Southern South America"),
                            ("ANDES", "Andean Region"),
                            ("CONO_SUR", "Cono Sur (Southern Cone)"),
                            ("NORTH_AFRICA", "North Africa"),
                            ("WEST_AFRICA", "West Africa"),
                            ("EAST_AFRICA", "East Africa"),
                            ("CENTRAL_AFRICA", "Central Africa"),
                            ("SOUTH_AFRICA", "Southern Africa"),
                            ("AUSTRALIA_NEWZEALAND", "Australia & New Zealand"),
                            ("MELANESIA", "Melanesia"),
                            ("MICRONESIA", "Micronesia"),
                            ("POLYNESIA", "Polynesia"),
                            ("GULF", "Gulf States"),
                            ("LEVANT", "Levant"),
                            ("PERSIAN", "Persian Region"),
                        ],
                        verbose_name="specific world sector",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="is-active-country"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "area_name",
                    models.CharField(max_length=150, verbose_name="name-of-area"),
                ),
                (
                    "area_code",
                    models.CharField(
                        max_length=3, null=True, unique=True, verbose_name="area-code"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="description of the area location",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="is-active-area"),
                ),
                (
                    "established_date",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="established-date"
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="locations.chapterlocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("area_name", "chapter")},
            },
        ),
        migrations.AddField(
            model_name="chapterlocation",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="locations.clusterlocation",
            ),
        ),
        migrations.AddField(
            model_name="clusterlocation",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="locations.countrylocation",
            ),
        ),
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField(max_length=500)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "poi_type",
                    models.CharField(
                        choices=[
                            ("ACCOMMODATION", "Accommodation"),
                            ("VENUE", "Venue"),
                            ("SPORTS_VENUE", "Sports Venue"),
                            ("PUBLIC_TRANSPORT", "Public Transport"),
                            ("TRANSPORT", "Transport"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venues_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venues_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelativeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="name of relative location"
                    ),
                ),
                (
                    "relative_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relative_search_areas",
                        to="locations.arealocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venues_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue",
                        to="locations.poi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_venues_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="locations.venue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VenueContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[core.utils.validators.PhoneNumberValidator()],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANAGER", "Manager"),
                            ("OWNER", "Owner"),
                            ("COORDINATOR", "Coordinator"),
                            ("SUPPORT", "Support"),
                            ("OTHER", "Other"),
                        ],
                        default="OWNER",
                        max_length=100,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venue_contacts_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="locations.venue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VenueMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Enter a label for the metadata. E.g. Distance from main venue",
                        max_length=255,
                        verbose_name="Metadata Label",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Enter the metadata value here. E.g. 300M away from venue",
                        null=True,
                        verbose_name="Metadata Value",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venue_metadata_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_metadata",
                        to="locations.poi",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="locations.venue",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="chapterlocation",
            unique_together={("chapter_name", "cluster")},
        ),
    ]
