# Generated by Django 5.1.5 on 2025-12-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="arealocation",
            constraint=models.UniqueConstraint(
                fields=("area_code", "chapter"), name="unique_area_code_per_chapter"
            ),
        ),
    ]
