# Generated by Django 5.1.5 on 2026-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_arealocation_unique_area_code_per_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealocation',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='established-date'),
        ),
        migrations.AlterField(
            model_name='chapterlocation',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='established-date'),
        ),
        migrations.AlterField(
            model_name='clusterlocation',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='established-date'),
        ),
    ]
