# Generated by Django 5.1.5 on 2026-06-03 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_arealocation_latitude_arealocation_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=0, help_text='0 = ground floor, increment upward')),
                ('level_label', models.CharField(blank=True, help_text='Optional human-readable label, e.g. "Mezzanine"', max_length=100)),
                ('image', models.ImageField(upload_to='floor_plans/')),
                ('original_width', models.PositiveIntegerField(help_text='Pixel width of the uploaded image, extracted server-side')),
                ('original_height', models.PositiveIntegerField(help_text='Pixel height of the uploaded image, extracted server-side')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plans_added', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='locations.venue')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlanAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('colour', models.CharField(default='#4F46E5', help_text='Hex colour string used for rendering the polygon on the canvas', max_length=20)),
                ('vertices', models.JSONField(help_text='List of {x: float, y: float} normalised coordinate objects (min 3 points)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_annotations_added', to=settings.AUTH_USER_MODEL)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='locations.floorplan')),
                ('room_venue', models.ForeignKey(blank=True, help_text='Optional link to an existing room in this venue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_annotations', to='locations.roomvenue')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlanAnnotationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_annotation_metadata_added', to=settings.AUTH_USER_MODEL)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='locations.floorplanannotation')),
            ],
        ),
    ]
