# Generated by Django 5.1.5 on 2026-06-04 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_eventvenue_is_primary'),
        ('locations', '0005_floorplan_floorplanannotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='event_venue',
            field=models.ForeignKey(blank=True, help_text='Optional link to an EventVenue snapshot for historical reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plans', to='events.eventvenue'),
        ),
    ]
