# Generated by Django 5.1.5 on 2026-06-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_eventreview_is_public_alter_eventreview_approved_and_more'),
        ('locations', '0006_floorplan_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplanannotation',
            name='room_venue',
            field=models.ForeignKey(blank=True, help_text='Optional link to an existing room in this venue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_annotations', to='events.eventvenueroom'),
        ),
    ]
