# Generated by Django 5.1.5 on 2025-12-24 19:46

import django.db.models.deletion
import timezone_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("target_id", models.PositiveIntegerField()),
                ("public", models.BooleanField(default=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                            ("LINK", "Link"),
                            ("OTHER", "Other"),
                        ],
                        default="DOCUMENT",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="resources/files/"
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="resources/images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvailabilityWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "availability_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "availability_type",
                    models.CharField(
                        choices=[
                            ("REFUND_WINDOW", "Refund Window"),
                            ("REGISTRATION_WINDOW", "Registration Window"),
                            ("MERCHANDISE_WINDOW", "Merchandise Window"),
                            ("DONATION_WINDOW", "Donation Window"),
                            ("PAYMENT_WINDOW", "Payment Window"),
                            ("PRODUCT_WINDOW", "Product Window"),
                            ("DISCOUNT_WINDOW", "Discount Window"),
                            ("RESOURCE_WINDOW", "Resource Window"),
                            ("PAYMENT_PACKAGE_WINDOW", "Payment Package Window"),
                        ],
                        default="REGISTRATION_WINDOW",
                        max_length=30,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("available_from", models.DateTimeField()),
                ("available_to", models.DateTimeField()),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(default="Europe/London"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["availability_id"],
                        name="common_avai_availab_dad2d2_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="common_avai_target__b5959f_idx",
                    ),
                ],
            },
        ),
    ]
