# Generated by Django 5.1.5 on 2025-12-24 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="common_reso_target__2ff305_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type"], name="common_reso_resourc_e60143_idx"
            ),
        ),
    ]
