# Generated by Django 5.1.5 on 2025-12-25 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_resource_common_reso_target__2ff305_idx_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="protected",
            field=models.BooleanField(
                default=False,
                help_text="If true, the resource cannot be deleted automatically.  ",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text="Tag for categorizing the resource, e.g., LANDING_PHOTO, SCHEDULE_PDF, SPEAKER_BIO, etc. Database only.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["tag"], name="common_reso_tag_d9b010_idx"),
        ),
    ]
