# Generated by Django 5.1.5 on 2025-12-30 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_resource_protected_resource_tag_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('IS_EVENT_STAFF', 'Is Event Staff'), ('IS_AGE_LT', 'Is Age Less Than'), ('IS_AGE_GT', 'Is Age Greater Than'), ('ORGANISATION_MATCHES', 'Organisation Matches'), ('VALUE_MATCHES', 'Value Matches'), ('EVENT_STAFF_ROLE_MATCHES', 'Event Staff Role Matches'), ('NAME_MATCHES', 'Name Matches'), ('LOCATION_MATCHES', 'Location Matches'), ('CODE_MATCHES', 'Code Matches')], default='IS_EVENT_STAFF', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.CharField(blank=True, help_text='Value associated with the rule (e.g. age limit, organisation name, etc.)', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_id', models.PositiveIntegerField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
