# Generated by Django 5.1.5 on 2026-01-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_accessrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='resources/files/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='resources/images/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='target_id',
            field=models.CharField(max_length=255),
        ),
    ]
