# Generated by Django 5.1.5 on 2026-01-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_resource_file_alter_resource_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name']},
        ),
    ]
