# Generated by Django 5.1.5 on 2026-02-01 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_resource_options'),
        ('organisations', '0006_leader_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityWindowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_predefined', models.BooleanField(default=False)),
                ('windows_config', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_templates', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_templates', to='organisations.organisation')),
            ],
            options={
                'ordering': ['is_predefined', '-created_at'],
                'indexes': [models.Index(fields=['template_id'], name='common_avai_templat_5587f8_idx'), models.Index(fields=['is_predefined'], name='common_avai_is_pred_0ffe4c_idx'), models.Index(fields=['organisation'], name='common_avai_organis_afe078_idx')],
            },
        ),
    ]
