# Generated by Django 5.1.5 on 2026-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_availabilitywindowtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitywindow',
            name='availability_type',
            field=models.CharField(choices=[('REFUND_WINDOW', 'Refund Window'), ('REGISTRATION_WINDOW', 'Registration Window'), ('MERCHANDISE_WINDOW', 'Merchandise Window'), ('DONATION_WINDOW', 'Donation Window'), ('PAYMENT_WINDOW', 'Payment Window'), ('PRODUCT_WINDOW', 'Product Window'), ('PRODUCT_PREVIEW_WINDOW', 'Product Preview Window'), ('DISCOUNT_WINDOW', 'Discount Window'), ('RESOURCE_WINDOW', 'Resource Window'), ('PAYMENT_PACKAGE_WINDOW', 'Payment Package Window'), ('PAYMENT_PACKAGE_PREVIEW_WINDOW', 'Payment Package Preview Window')], default='REGISTRATION_WINDOW', max_length=30),
        ),
    ]
