# Generated by Django 5.1.5 on 2026-04-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_availabilitywindow_availability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration date for the resource. If set, the resource will be considered expired after this date.', null=True),
        ),
    ]
