# Generated by Django 5.1.5 on 2026-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_resource_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
