# Generated by Django 5.1.5 on 2025-12-24 11:54

import django.db.models.deletion
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_name", models.CharField(blank=True, max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile-pictures/"
                    ),
                ),
                (
                    "profile_picture_uploaded_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("preferred_language", models.CharField(blank=True, max_length=50)),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(default="Europe/London"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
