# Generated by Django 5.1.5 on 2026-01-02 11:23

import core.utils.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_arealocation_unique_area_code_per_chapter'),
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='area_from',
            field=models.ForeignKey(blank=True, help_text='The area where the user is from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.arealocation', verbose_name='Area From'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.utils.validators.PhoneNumberValidator()]),
        ),
    ]
