# Generated by Django 5.1.5 on 2026-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options_profile_area_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ecclesiastical_rank',
            field=models.CharField(blank=True, choices=[('priest', 'Priest'), ('deacon', 'Deacon'), ('nun', 'Nun'), ('cardinal', 'Cardinal'), ('major_archbishop', 'Major Archbishop'), ('archbishop', 'Archbishop'), ('diocesan_bishop', 'Diocesan Bishop'), ('auxiliary_bishop', 'Auxiliary Bishop'), ('dean', 'Dean'), ('pastor', 'Pastor'), ('assistant_pastor', 'Assistant Pastor'), ('assistant_priest', 'Assistant Priest'), ('transitional_deacon', 'Transitional Deacon'), ('permanent_deacon', 'Permanent Deacon'), ('sister', 'Sister'), ('brother', 'Brother'), ('abbot', 'Abbot'), ('abbess', 'Abbess'), ('monk', 'Monk'), ('friar', 'Friar'), ('other', 'Other')], help_text='The ecclesiastical rank of the user, if applicable.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='ecclesiastical_status',
            field=models.CharField(blank=True, choices=[('clergy', 'Clergy'), ('religious', 'Religious'), ('laity', 'Laity')], help_text='The ecclesiastical status of the user, if applicable.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_clergy_or_religious',
            field=models.BooleanField(default=False, help_text='Whether the user is clergy or religious.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the profile is visible to others.'),
        ),
    ]
