# Generated by Django 5.1.5 on 2025-12-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0004_attendeeorganisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilityrequirement",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="dietaryrequirement",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="medicalcondition",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
