# Generated by Django 5.1.5 on 2025-12-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0005_alter_accessibilityrequirement_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
