# Generated by Django 5.1.5 on 2025-12-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0006_alter_attendee_date_of_birth"),
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendees",
                to="bookings.booking",
            ),
        ),
    ]
