# Generated by Django 5.1.5 on 2025-12-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0007_attendee_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeaccessibilityrequirement",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendeedietaryrequirement",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendeemedicalcondition",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
