# Generated by Django 5.1.5 on 2025-12-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0008_attendeeaccessibilityrequirement_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="relationship_to_user",
            field=models.CharField(
                choices=[
                    ("self", "Self"),
                    ("spouse", "Spouse"),
                    ("child", "Child"),
                    ("friend", "Friend"),
                    ("parent", "Parent"),
                    ("sibling", "Sibling"),
                    ("other", "Other"),
                ],
                default="self",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendeeguardian",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("self", "Self"),
                    ("spouse", "Spouse"),
                    ("child", "Child"),
                    ("friend", "Friend"),
                    ("parent", "Parent"),
                    ("sibling", "Sibling"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
