# Generated by Django 5.1.5 on 2026-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0011_accessibilityrequirement_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityrequirement',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendeeaccessibilityrequirement',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendeedietaryrequirement',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendeemedicalcondition',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietaryrequirement',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
    ]
