# Generated by Django 5.1.5 on 2026-01-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0012_accessibilityrequirement_auto_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeemedicalcondition',
            name='severity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
