# Generated by Django 5.1.5 on 2026-01-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0013_attendeemedicalcondition_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeemedicalcondition',
            name='severity',
            field=models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=100, null=True),
        ),
    ]
