# Generated by Django 5.1.5 on 2026-01-12 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0014_alter_attendeemedicalcondition_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
