# Generated by Django 5.1.5 on 2026-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0015_alter_attendee_first_name_alter_attendee_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilityrequirement',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
