# Generated by Django 5.1.5 on 2026-03-14 11:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_familygroup_event_and_organisation(apps, schema_editor):
    FamilyGroup = apps.get_model('attendee', 'FamilyGroup')
    FamilyAttendee = apps.get_model('attendee', 'FamilyAttendee')

    # Backfill each family group from its first linked attendee.
    for family_group in FamilyGroup.objects.filter(event__isnull=True).iterator():
        first_member = (
            FamilyAttendee.objects
            .filter(family_group_id=family_group.id, attendee__event__isnull=False)
            .select_related('attendee__event__organisation')
            .order_by('id')
            .first()
        )

        if not first_member:
            continue

        attendee_event = first_member.attendee.event
        if not attendee_event:
            continue

        family_group.event_id = attendee_event.id
        family_group.organisation_id = attendee_event.organisation_id
        family_group.save(update_fields=['event', 'organisation'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0016_alter_accessibilityrequirement_code_and_more'),
        ('events', '0024_alter_eventpermission_category'),
        ('organisations', '0007_locationleaderinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_groups', to='events.event'),
        ),
        migrations.AddField(
            model_name='familygroup',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_groups', to='organisations.organisation'),
        ),
        migrations.RunPython(backfill_familygroup_event_and_organisation, noop_reverse),
    ]
