# Generated by Django 5.1.5 on 2026-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0017_familygroup_event_familygroup_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled'), ('whitelisted', 'Whitelisted')], default='registered', max_length=20),
        ),
    ]
