# Generated by Django 5.1.5 on 2026-03-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0018_attendee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('registered', 'Registered'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled'), ('whitelisted', 'Whitelisted')], default='registered', max_length=20),
        ),
    ]
