# Generated by Django 5.1.5 on 2026-05-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0019_alter_attendee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('registered', 'Registered'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('whitelisted', 'Whitelisted')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendeeaction',
            name='action',
            field=models.CharField(choices=[('registered', 'Registered'), ('made_payment', 'Made Payment'), ('cancelled_payment', 'Cancelled Payment'), ('intends_to_refund_payment', 'Intends to Refund Payment'), ('ordered_from_shop', 'Ordered from Shop'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('updated_info', 'Updated Information')], default='registered', max_length=50),
        ),
    ]
