# Generated by Django 5.1.5 on 2026-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0020_alter_attendee_status_alter_attendeeaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
