# Generated by Django 5.1.5 on 2026-05-20 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0021_alter_consent_code'),
        ('bookings', '0017_bookingpackage_original_amount_and_more'),
        ('events', '0033_event_closed_message_event_published_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeCheckIn',
            fields=[
                ('check_in_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], default='CHECK_IN', max_length=20)),
                ('method', models.CharField(choices=[('QR_CODE', 'QR Code'), ('MANUAL', 'Manual'), ('ADMIN', 'Admin')], default='MANUAL', max_length=20)),
                ('scan_result', models.CharField(choices=[('SUCCESS', 'Success'), ('ALREADY_CHECKED_IN', 'Already Checked In'), ('ALREADY_CHECKED_OUT', 'Already Checked Out'), ('INVALID_TICKET', 'Invalid Ticket'), ('CANCELLED_ATTENDEE', 'Cancelled Attendee'), ('CANCELLED_TICKET', 'Cancelled Ticket'), ('NOT_FOUND', 'Not Found'), ('OUTSTANDING_PAYMENTS', 'Outstanding Payments'), ('ERROR', 'Error')], default='SUCCESS', max_length=30)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attendee_status_snapshot', models.CharField(blank=True, max_length=30)),
                ('has_outstanding_payments', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('alternative_signin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_records', to='bookings.attendeealternativesigninidentifier')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_records', to='attendee.attendee')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_check_ins', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_records', to='bookings.ticket')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_records', to='events.eventvenue')),
                ('venue_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_records', to='events.eventvenueroom')),
            ],
            options={
                'verbose_name': 'Attendee Check-In',
                'verbose_name_plural': 'Attendee Check-Ins',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['attendee', 'performed_at'], name='attendee_at_attende_44b68b_idx'), models.Index(fields=['performed_at'], name='attendee_at_perform_b8b1de_idx')],
            },
        ),
    ]
