# Generated by Django 5.1.5 on 2026-05-21 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0023_alter_attendeeaction_performed_by'),
        ('bookings', '0017_bookingpackage_original_amount_and_more'),
        ('events', '0033_event_closed_message_event_published_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeecheckin',
            name='event_day',
            field=models.IntegerField(blank=True, db_index=True, help_text='Calendar day relative to event start (Day 1 = event start date in event timezone). Negative values indicate check-ins before the event window; values beyond the event duration indicate check-ins after the event.', null=True),
        ),
        migrations.AddIndex(
            model_name='attendeecheckin',
            index=models.Index(fields=['event_day', 'performed_at'], name='attendee_at_event_d_c34d92_idx'),
        ),
    ]
