# Generated by Django 5.1.5 on 2026-06-09 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0024_attendeecheckin_event_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=1000, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='attendee.attendee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendee_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendee Note',
                'verbose_name_plural': 'Attendee Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
