# Generated by Django 5.1.5 on 2025-12-25 22:15

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0007_attendee_booking"),
        ("bookings", "0002_initial"),
        ("events", "0008_alter_eventroleassignment_unique_together"),
        ("payments", "0002_paymentmethod_payment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="attendee",
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_code"], name="bookings_ti_ticket__47846c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="bookings_ti_status_90f1ac_idx"),
        ),
        migrations.AddConstraint(
            model_name="bookingpackage",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="unique_booking_package_name_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("attendee", "ticket_type", "status"),
                name="unique_active_ticket_per_attendee_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.UniqueConstraint(
                fields=("event", "title"), name="unique_ticket_type_title_per_event"
            ),
        ),
    ]
