# Generated by Django 5.1.5 on 2025-12-25 22:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_remove_booking_attendee_ticket_ticket_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="id",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
