# Generated by Django 5.1.5 on 2025-12-25 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_remove_ticket_id_alter_ticket_ticket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="The booking package used for pricing this ticket",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="bookings.bookingpackage",
            ),
        ),
    ]
