# Generated by Django 5.1.5 on 2025-12-31 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0011_accessibilityrequirement_processed_at_and_more'),
        ('bookings', '0006_alter_bookingpackagerule_rule_type'),
        ('events', '0014_alter_event_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAlternativeSigninIdentifier',
            fields=[
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('verified_updated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('format_match', models.CharField(blank=True, help_text='A regex pattern to match the identifier format.', max_length=255, null=True, verbose_name='Format Match')),
                ('max_uses_per_signin', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Uses Per Sign-in')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_signins', to='events.event', verbose_name='Event')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Alternative Sign-in Identifier',
                'verbose_name_plural': 'Event Alternative Sign-in Identifiers',
                'unique_together': {('event', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AttendeeAlternativeSigninIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Sign ID')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('defined_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Uses')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_signins', to='attendee.attendee', verbose_name='Attendee')),
                ('defined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defined_attendee_alternative_signins', to=settings.AUTH_USER_MODEL, verbose_name='Defined By')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_alternative_signins', to='bookings.ticket', verbose_name='Ticket')),
                ('event_alternative_signin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_identifiers', to='bookings.eventalternativesigninidentifier', verbose_name='Event Alternative Sign-in Identifier')),
            ],
            options={
                'unique_together': {('attendee', 'event_alternative_signin', 'identifier')},
            },
        ),
    ]
