# Generated by Django 5.1.5 on 2025-12-31 20:58

import apps.payments.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_eventalternativesigninidentifier_and_more'),
        ('products', '0006_productcategory_eventproductcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('verified_updated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_per_attendee', models.PositiveIntegerField(default=1, verbose_name='Quantity Per Attendee')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_package_products', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('booking_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_products', to='bookings.bookingpackage', verbose_name='Booking Package')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_packages', to='products.product', verbose_name='Product')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package Product',
                'verbose_name_plural': 'Package Products',
                'ordering': ['-added_at'],
                'unique_together': {('booking_package', 'product')},
            },
            bases=(models.Model, apps.payments.mixins.DiscountMixin),
        ),
    ]
