# Generated by Django 5.1.5 on 2026-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_bookingpackage_percentage_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventalternativesigninidentifier',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
    ]
