# Generated by Django 5.1.5 on 2026-01-10 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_eventalternativesigninidentifier_auto_processed'),
        ('events', '0015_alter_eventpermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingIntent',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booking_intent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intended_ticket_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_intents', to='events.event')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_booking_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Intent',
                'verbose_name_plural': 'Booking Intents',
                'ordering': ['-created_at'],
            },
        ),
    ]
