# Generated by Django 5.1.5 on 2026-01-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_bookingintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingintent',
            name='complete_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingintent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
