# Generated by Django 5.1.5 on 2026-01-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_bookingintent_complete_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
