# Generated by Django 5.1.5 on 2026-01-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
