# Generated by Django 5.1.5 on 2026-03-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_tickettype_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingintent',
            name='completed_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_intent', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingintent',
            name='last_checkout_idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
