# Generated by Django 5.1.5 on 2026-06-07 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0024_attendeecheckin_event_day_and_more'),
        ('bookings', '0017_bookingpackage_original_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('verified_updated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_processed', models.BooleanField(default=False)),
                ('transport_booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(blank=True, help_text='Unique reference code for the transport booking. This will be auto-generated if not provided.', max_length=50, null=True, unique=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information related to the transport booking (e.g., special requirements).', null=True)),
                ('expiry_datetime', models.DateTimeField(blank=True, help_text='Date and time when the transport booking expires (if applicable).', null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Whether the transport booking is valid. This can be used to automatically invalidate bookings that have passed their expiry date.')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Whether the transport booking has been cancelled.')),
                ('attendee', models.ForeignKey(help_text='The attendee who the booking is for', on_delete=django.db.models.deletion.CASCADE, related_name='transport_bookings', to='attendee.attendee')),
                ('made_by', models.ForeignKey(blank=True, help_text='User who made the transport booking. This can be the attendee themselves or an admin/staff member making the booking on behalf of the attendee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_bookings_made', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transport Booking',
                'verbose_name_plural': 'Transport Bookings',
            },
        ),
    ]
