# Generated by Django 5.1.5 on 2026-06-07 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_transportbooking'),
        ('events', '0036_eventtransportoption_eventtransportschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbooking',
            name='transport_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.eventtransportoption'),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
