# Generated by Django 5.1.5 on 2026-06-08 11:39

import apps.bookings.models.delegation
import core.utils.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0024_attendeecheckin_event_day_and_more'),
        ('bookings', '0019_transportbooking_transport_option_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('verified_updated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_processed', models.BooleanField(default=False)),
                ('delegation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255)])),
                ('type', models.CharField(choices=[('country', 'Country'), ('area', 'Area'), ('chapter', 'Chapter'), ('cluster', 'Cluster'), ('company', 'Company'), ('organisation', 'Organisation'), ('parish', 'Parish'), ('community', 'Community'), ('group', 'Group'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for the delegation. At least one contact method (email or phone) must be provided.', max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone for the delegation. At least one contact method (email or phone) must be provided.', max_length=20, null=True, validators=[core.utils.validators.PhoneNumberValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_created', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DelegationHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('youth_head', 'Youth Head'), ('adult_head', 'Adult Head'), ('other', 'Other')], default='other', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_heads_added', to=settings.AUTH_USER_MODEL)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_heads', to='attendee.attendee')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='bookings.delegation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_heads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DelegationHeadInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('verified_updated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_processed', models.BooleanField(default=False)),
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('youth_head', 'Youth Head'), ('adult_head', 'Adult Head'), ('other', 'Other')], default='other', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, default=apps.bookings.models.delegation.default_expires_at, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_head_invites_accepted', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_invites', to='bookings.delegation')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_head_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_head_invites', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
