# Generated by Django 5.1.5 on 2025-12-25 14:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_eventsponsor_eventsponsorpackage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventsponsorpackage",
            old_name="amount",
            new_name="base_amount",
        ),
        migrations.RenameField(
            model_name="eventsponsorpackage",
            old_name="amount_currency",
            new_name="base_amount_currency",
        ),
        migrations.AddField(
            model_name="eventsponsorpackage",
            name="percentage_modifier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage adjustment applied to the base amount (e.g. -10 for 10% discount).",
                max_digits=5,
            ),
        ),
    ]
