# Generated by Django 5.1.5 on 2026-01-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_alter_eventsponsorpackage_percentage_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_leaders', to='organisations.organisation'),
        ),
    ]
