# Generated by Django 5.1.5 on 2026-03-13 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_leader_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLeaderInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('country', 'Country'), ('cluster', 'Cluster'), ('chapter', 'Chapter'), ('area', 'Area')], max_length=20)),
                ('location_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_invites', to='organisations.organisation')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['organisation', 'location_type', 'location_id'], name='organisatio_organis_f07392_idx'), models.Index(fields=['target_user', 'is_active', 'accepted'], name='organisatio_target__f6232c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted', False), ('is_active', True)), fields=('organisation', 'target_user', 'location_type', 'location_id'), name='uniq_active_pending_location_leader_invite')],
            },
        ),
    ]
