# Generated by Django 5.1.5 on 2026-03-15 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_eventpermission_category'),
        ('locations', '0003_alter_arealocation_established_date_and_more'),
        ('organisations', '0007_locationleaderinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsponsor',
            options={'verbose_name': 'Event Sponsor', 'verbose_name_plural': 'Event Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='eventsponsorpackage',
            options={'ordering': ['tier'], 'verbose_name': 'Event Sponsor Package', 'verbose_name_plural': 'Event Sponsor Packages'},
        ),
        migrations.AlterUniqueTogether(
            name='eventsponsorpackage',
            unique_together={('event', 'package_name')},
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='chapter_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='locations.chapterlocation'),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='organisations.eventsponsorpackage'),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='verified_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsponsorpackage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsponsorpackage',
            name='tier',
            field=models.PositiveIntegerField(default=1, help_text='Sponsorship tier (e.g., 1 for Gold, 2 for Silver, etc.)'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsponsor',
            unique_together={('event', 'organisation', 'chapter_location', 'package')},
        ),
        migrations.RemoveField(
            model_name='eventsponsorpackage',
            name='sponsor',
        ),
    ]
