# Generated by Django 5.1.5 on 2026-03-15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_alter_eventsponsor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsponsor',
            name='sponsor_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='eventsponsorpackage',
            name='package_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventsponsor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='eventsponsorpackage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='eventsponsor',
            constraint=models.UniqueConstraint(
                fields=('event', 'organisation', 'chapter_location'),
                name='unique_event_sponsor_per_org_location',
            ),
        ),
        migrations.AddConstraint(
            model_name='eventsponsorpackage',
            constraint=models.UniqueConstraint(
                fields=('event', 'package_name'),
                name='unique_sponsor_package_name_per_event',
            ),
        ),
        migrations.AddConstraint(
            model_name='eventsponsorpackage',
            constraint=models.UniqueConstraint(
                fields=('event', 'tier'),
                name='unique_sponsor_package_tier_per_event',
            ),
        ),
    ]
