# Generated by Django 5.1.5 on 2026-03-16

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventsettings'),
        ('locations', '0001_initial'),
        ('organisations', '0009_eventsponsor_uuid_and_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSponsorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('chapter_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_invites', to='locations.chapterlocation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_invites', to='events.event')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_invites', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Event Sponsor Invite',
                'verbose_name_plural': 'Event Sponsor Invites',
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='unique_sponsor_invite_per_event_email')],
            },
        ),
    ]
