# Generated by Django 5.1.5 on 2026-04-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_eventsponsorinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='short_description',
            field=models.CharField(blank=True, help_text='A short description of the organisation for display in lists and summaries.', max_length=500),
        ),
        migrations.AddField(
            model_name='organisation',
            name='url_safe_title',
            field=models.CharField(blank=True, help_text='URL-safe version of the title, auto-generated if not provided.', max_length=255, null=True, unique=True),
        ),
    ]
