# Generated by Django 5.1.5 on 2026-05-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_eventsponsorpackage_original_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='initially_sponsorship',
            field=models.BooleanField(default=False, help_text='Indicates whether the organisation is an initial sponsor. This can be used to highlight certain organisations on the platform.'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the organisation has been verified by an admin. This is separate from membership verification and can be used to denote that the organisation itself is legitimate or approved.'),
        ),
    ]
