# Generated by Django 5.1.5 on 2026-06-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_organisation_initially_sponsorship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='parent_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organisations', to='organisations.organisation'),
        ),
    ]
