# Generated by Django 5.1.5 on 2026-06-04 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_eventvenue_is_primary'),
        ('organisations', '0014_organisation_parent_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationEventPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_external_events', models.BooleanField(default=False, help_text='Whether events under this organisation can be created by external users.')),
                ('allow_attendee_deletions', models.BooleanField(default=False, help_text='Whether attendees can be deleted from events under this organisation.')),
                ('allow_workshops', models.BooleanField(default=True, help_text='Whether events under this organisation can be workshops.')),
                ('allow_product_releases', models.BooleanField(default=True, help_text='Whether events under this organisation can have product releases.')),
                ('allow_sponsors', models.BooleanField(default=True, help_text='Whether events under this organisation can have sponsors.')),
                ('require_long_description', models.BooleanField(default=False, help_text='Whether events under this organisation must have a long description.')),
                ('require_short_description', models.BooleanField(default=False, help_text='Whether events under this organisation must have a short description.')),
                ('require_landing_image', models.BooleanField(default=False, help_text='Whether events under this organisation must have a landing image.')),
                ('product_release_must_be_approved_by_organisation', models.BooleanField(default=True, help_text='Whether product releases must be approved by the organisation.')),
                ('must_be_approved_by_organisation', models.BooleanField(default=True, help_text='Whether events must be approved by the organisation.')),
                ('max_attendees_per_event', models.PositiveIntegerField(default=100, help_text='The maximum number of attendees allowed for events under this organisation. Set to 0 for unlimited.')),
                ('max_events_per_organiser', models.PositiveIntegerField(default=10, help_text='The maximum number of events an organiser can create under this organisation. Set to 0 for unlimited.')),
                ('card_payments_are_allowed', models.BooleanField(default=True, help_text='Whether card payments are allowed for events under this organisation.')),
                ('bank_transfers_are_allowed', models.BooleanField(default=True, help_text='Whether bank transfers are allowed for events under this organisation.')),
                ('max_package_price', models.DecimalField(decimal_places=2, default=1000.0, help_text='The maximum price for event packages under this organisation.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_policies', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_policy', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationEventTypePolicyRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True, help_text='Whether this event type is allowed for events under this organisation.')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether events of this type require approval from the organisation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_type_restrictions', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_restrictions', to='events.eventtype')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type_restrictions', to='organisations.organisation')),
            ],
        ),
    ]
