# Generated by Django 5.1.5 on 2026-06-04 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0015_organisationeventpolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(choices=[('allow_event_approval', 'Allow Event Approval'), ('allow_manage_leaders', 'Allow Managing Leaders'), ('allow_manage_organisation', 'Allow Managing Organisation'), ('allow_membership_access', 'Allow Access to Membership Information'), ('allow_organisation_sponsor', 'Allow Sponsoring the Organisation'), ('allow_policy_management', 'Allow Managing Organisation Policies'), ('allow_data_management', 'Allow Managing Organisation Data'), ('allow_review_access', 'Allow Access to Reviews and Feedback'), ('allow_monetary_access', 'Allow Access to Monetary Transactions'), ('allow_landing_page_management', 'Allow Managing Organisation Landing Page')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('allow_create', models.BooleanField(default=False, help_text='Whether this permission allows create access.')),
                ('allow_read', models.BooleanField(default=True, help_text='Whether this permission allows read access.')),
                ('allow_update', models.BooleanField(default=False, help_text='Whether this permission allows update access.')),
                ('allow_delete', models.BooleanField(default=False, help_text='Whether this permission allows delete access.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='organisations.leader')),
            ],
            options={
                'unique_together': {('leader', 'permission_code')},
            },
        ),
    ]
